trigger:
  branches:
    include:
    - dev
    - prd

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9.x'

# Install dependencies
- script: |
    echo 'Installing dependencies'
    pip install -r requirements.txt
  displayName: 'Install Python dependencies'

# Deploy to mydev
- script: |
    echo 'Deploying to mydev'
    bobsled deploy -e mydev -d demo -s opendata
  displayName: 'Deploy to mydev'
  condition: eq(variables['Build.SourceBranchName'], 'mydev')
  env:
    PRIVATE_KEY: $(PRIVATE_KEY)

# Deploy to prdbranch
- script: |
    echo 'Deploying to prdbranch'
    bobsled deploy -e prdbranch -d demo_dev -s opendata
  displayName: 'Deploy to prdbranch'
  condition: eq(variables['Build.SourceBranchName'], 'prdbranch')
  env:
    SNOWFLAKE_PWD: $(SNOWFLAKE_PWD)
