trigger:
  branches:
    include:
    - dev
    - prd

pool:
  vmImage: 'ubuntu-latest'

# Set variables based on branch
variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'dev') }}:
    - group: dev_account
  - ${{ if eq(variables['Build.SourceBranchName'], 'prd') }}:
    - group: prd_account

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.9.x'
  inputs:
    versionSpec: '3.9.x'

# Download connections.toml
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'connections.toml'
  displayName: 'Download connections.toml'

# Move connections.toml file to correct location
- script: |
    mkdir -p ~/.snowflake
    mv $(Agent.TempDirectory)/connections.toml ~/.snowflake/connections.toml
  displayName: 'Move connections.toml to Snowflake folder'

# Install dependencies and Bobsled
- script: |
    echo 'Installing dependencies'
    pip install -r requirements.txt
    pip install -e .
  displayName: 'Install Python dependencies and Bobsled'

# Deploy to mydev
- task: Bash@3
  displayName: 'Run Dev Deployment'
  inputs:
    targetType: 'inline'
    script: |
      echo 'Deploying to mydev'
      bobsled deploy -e mydev -d demo -s opendata
  condition: eq(variables['Build.SourceBranchName'], 'dev')
  env:
    PRIVATE_KEY: $(PRIVATE_KEY)

# Deploy to prdbranch
- task: Bash@3
  displayName: 'Run PRD Deployment'
  inputs:
    targetType: 'inline'
    script: |
      echo 'Deploying to prdbranch'
      bobsled deploy -e prdbranch -d demo_dev -s opendata
  condition: eq(variables['Build.SourceBranchName'], 'prd')
  env:
    SNOWFLAKE_PWD: $(SNOWFLAKE_PWD)