trigger:
  branches:
    include:
    - dev
    - prd

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.9.x'
  inputs:
    versionSpec: '3.9.x'

# Download connections.toml
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'connections.toml'
  displayName: 'Download connections.toml'

# Download rsa_key.der file for mydev
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'rsa_key.der'
  displayName: 'Download rsa_key.der for mydev'

# Move connections.toml file and rsa_key.der to correct location
# Dynamically update the private key path in connections.toml
# Extract local private_key_path and replace it with Linux path
- script: |
    mkdir -p ~/.snowflake
    mv $(Agent.TempDirectory)/connections.toml ~/.snowflake/connections.toml
    mv $(Agent.TempDirectory)/rsa_key.der ~/.snowflake/rsa_key.der
    local_key_path = $(grep 'private_key_path' ~/.snowflake/connections.toml | awk -F'=' '{print $2}' | tr -d ' "')
    sed -i 's|C:/Users/AryanSingh/rsa_key.der|/home/vsts/.snowflake/rsa_key.der|g' ~/.snowflake/connections.toml
  displayName: 'Move files to Snowflake folder'

# Install dependencies and SnowFlow
- script: |
    echo 'Installing dependencies'
    pip install -r requirements.txt
    pip install snowflow
  displayName: 'Install Python dependencies and SnowFlow'

# Deploy to mydev
- task: Bash@3
  displayName: 'Run Dev Deployment'
  inputs:
    targetType: 'inline'
    script: |
      echo 'Deploying to mydev'
      snowflow deploy -e mydev -d demo -s opendata
  condition: eq(variables['Build.SourceBranchName'], 'dev')

# Deploy to prdbranch
- task: Bash@3
  displayName: 'Run PRD Deployment'
  inputs:
    targetType: 'inline'
    script: |
      echo 'Deploying to prdbranch'
      snowflow deploy -e prdbranch -d demo_dev -s opendata
  condition: eq(variables['Build.SourceBranchName'], 'prd')
