trigger:
  branches:
    include:
    - dev
    - prd

pool:
  vmImage: 'ubuntu-latest'

# Set variables based on branch
variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'prd') }}:
    - group: prd_account

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.9.x'
  inputs:
    versionSpec: '3.9.x'

# Download connections.toml
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'connections.toml'
  displayName: 'Download connections.toml'

# Download rsa_key.der file for mydev
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'rsa_key.der'
  displayName: 'Download rsa_key.der for mydev'

# Move connections.toml file and rsa_key.der to correct location
- script: |
    mkdir -p ~/.snowflake
    mv $(Agent.TempDirectory)/connections.toml ~/.snowflake/connections.toml
    mv $(Agent.TempDirectory)/rsa_key.der ~/.snowflake/rsa_key.der
  displayName: 'Move files to Snowflake folder'

# Install dependencies and Bobsled
- script: |
    echo 'Installing dependencies'
    pip install -r requirements.txt
    pip install -e .
  displayName: 'Install Python dependencies and Bobsled'

# Deploy to mydev
- task: Bash@3
  displayName: 'Run Dev Deployment'
  inputs:
    targetType: 'inline'
    script: |
      echo 'Deploying to mydev'
      bobsled deploy -e mydev -d demo -s opendata
  condition: eq(variables['Build.SourceBranchName'], 'dev')

# Deploy to prdbranch
- task: Bash@3
  displayName: 'Run PRD Deployment'
  inputs:
    targetType: 'inline'
    script: |
      echo 'Deploying to prdbranch'
      bobsled deploy -e prdbranch -d demo_dev -s opendata
  condition: eq(variables['Build.SourceBranchName'], 'prd')
  env:
    SNOWFLAKE_PWD: $(SNOWFLAKE_PWD)