CREATE OR REPLACE TASK !!!TASK_NAME!!!
COMMENT = 'Programtically generated for !!!DAG_NAME!!!'
USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = '!!!INITIAL_WAREHOUSE_SIZE!!!'
!!!SCHEDULE!!!
!!!ROOT_VARIABLES!!!
!!!WHEN_CLAUSE!!!
AS
CALL !!!PROC_NAME!!!()
;