-- CREATE STORAGE IF NOT EXISTS INTEGRATION bobsled_azure_integration
--   TYPE = EXTERNAL_STAGE
--   STORAGE_PROVIDER = 'AZURE'
--   ENABLED = TRUE
--   AZURE_TENANT_ID = 'b2183828-8e6c-4cb5-b7b7-7211ac8de809'
--   STORAGE_ALLOWED_LOCATIONS = ('azure://mysfdemo.blob.core.windows.net/mysfcontainer/')
--   COMMENT = 'Azure Storage Integration for Bobsled';
